### ISSUE TITLE
Security Question

### ISSUE THREAD

**Issue by aus10powell** [ClarityNLP/ClarityNLP#100]
**Is this related to the code base or documentation?**
Code-based

**How urgent is this question?**
Mild

**What is your question?**
How secure is this environment? What data leaves my local environment when running? For example if I use your ingest App and upload a CSV is it all processed locally? Thanks! It looks like a cool tool.

**Comment by cahilton** [comment]
Everything is kept local unless you connect an algorithm that uses an outside API, but the default behavior keeps everything local. Our latest version uses OAuth 2.0 security and comes loaded with our own identity provider.
