### ISSUE TITLE
Lexical variant library

### ISSUE THREAD

**Issue by cahilton** [ClarityNLP/ClarityNLP#16]
Create a library/API that we can hook in to pipeline or wherever in ClarityNLP.  Should create plurals and other word forms (such as verb conjugations). This is different from synonyms and will apply to a word or phrase.

NLM has a library that does this, but I suspect we may not want to use in ClarityNLP. However, we can look at their approaches and review other approaches to this problem.

E.g. 
heart attack -> heart attacks
sleep -> sleeps, slept, sleeping

etc.

**Comment by cahilton** [comment]
NLM Library - https://www.nlm.nih.gov/research/umls/new_users/online_learning/LEX_004.html

**Comment by richardboyd** [comment]
Added pluralize.py to nlp/algorithms/vocabulary, which can be used to form plurals of words and phrases.

**Comment by richardboyd** [comment]
Added verb_inflector.py to nlp/algorithms/vocabulary to compute the standard English verb inflections.
