### ISSUE TITLE
Add a createReportTypeList for simple documentset creation

### ISSUE THREAD

**Issue by jduke99** [ClarityNLP/ClarityNLP#26]
Request:  A Clarity function createReportTypeList

Rationale: Our current createReportTagList is awesome and is the underpinnings of our interoperability.  That said, sometime you just want to import and run some documents using just the report type, without going over to the mapping API.  This also helps if you are running offline and don't have access to the GT servers but don't want to rebuild all the maps locally. 

Desired functionality:
documentset ProviderNotes:
    Clarity.createReportTypeList(["SomeReportTypeName"]);

Then it builds up the documenset WITHOUT having to go through the mapping APIs.  Just those report_type's are used in the solr query.

**Comment by cahilton** [comment]
```
documentset ProviderNotes:
    Clarity.createReportTypeList(["Discharge summary"]);
```
