### ISSUE TITLE
termset tester

### ISSUE THREAD

**Issue by cahilton** [ClarityNLP/ClarityNLP#29]
Create a way for users to test the params of termset, so they can see all the variations that will be included in their pipelines.

**Comment by cahilton** [comment]
Flags:
synonyms
plurals
verb inflection
descendant
ancestor terms

Pass in:
List of terms,  flags

Returns: 
list of terms

**Comment by richardboyd** [comment]
Checked in termset_expander.py to nlp/algorithms/vocabulary. This is a command-line tool that performs macro expansion for NLPQL termsets. Syntax is described in the docstring at the top of the file.

**Comment by richardboyd** [comment]
Branch 'ohdsi_synonyms' adds support for NLPQL macros in the OHDSI namespace (OHDSI.Synonyms(), OHDSI.Descendants(), OHDSI.Ancestors()).

**Comment by richardboyd** [comment]
Can use the new nlpql_expander API to test.
