### ISSUE TITLE
Support nested operations in NLPQL

### ISSUE THREAD

**Issue by cahilton** [ClarityNLP/ClarityNLP#59]
```
define final efValue:
    where EjectionFractionFunction.value < 50.0 OR EjectionFractionFunction.value >= 50.0;
```

**Comment by cahilton** [comment]
First pass at NLPQL was simple; passed straight to Pandas. Should evaluate all the operations for nested expressions.

**Comment by richardboyd** [comment]
The Mongo evaluator supports evaluation of nested expressions. Need a few more modifications to the NLPQL front end to fully support - will open a new ticket for that.
