### ISSUE TITLE
Root out instances of the "mutable default argument" problem

### ISSUE THREAD

**Issue by richardboyd** [ClarityNLP/ClarityNLP#85]
**Describe the bug**
A function parameter declared like this: 'param: list=list()' or 'param: dict=dict()' suffers from the Python "mutable default argument" bug. The default initializer runs only once, on the initial call to the function. Subsequent calls that omit those params are NOT default initialized.

**To Reproduce**
See this discussion on StackOverflow:

https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument

**Expected behavior**
Default initialization on each call is expected, but that only happens on the initial call.

**System Information:**
Observed on MacOSX with Anaconda python 3.6.4.

**Comment by cahilton** [comment]
Ooops. Looks like I missed some. Re-running inspector.

**Comment by cahilton** [comment]
From the PyCharm scan, they are all gone in nlp directory
